### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by MrPotatoHead-Dev** [Bunsly/HomeHarvest#100]
When trying to run the new version I keep getting stuck in a forever loop however when I run the same code on GoogleColab I get this warning: WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: [www.realtor.com](http://www.realtor.com/). Connection pool size: 10
Then it crashes: RetryError: HTTPSConnectionPool(host='[www.realtor.com](http://www.realtor.com/)', port=443): Max retries exceeded with url: /api/v1/rdc_search_srp?client_id=rdc-search-new-communities&schema=vesta (Caused by ResponseError('too many 403 error responses'))

**Comment by ZacharyHampton** [comment]
You're being blocked by Cloudfront, use a solid proxy here to get around this issue.
