### ISSUE TITLE
where can we support/tip the team

### ISSUE THREAD

**Issue by mlee33-nor** [Bunsly/HomeHarvest#103]
Hi! I just wanted to say this being free has seriously helped me so much in my business... i'm struggling a lot right now and wouldn't be able to afford a costly subscription as im still building my business.

Do you have a link where we can go and support / tip the creators of this  occasionally?

**Comment by cullenwatson** [comment]
thanks, never thought about payment haha but here's a sponshorship I created if you'd like. let me know if you want anything added to homeharvest

https://github.com/sponsors/Bunsly
