### ISSUE TITLE
Traceback (most recent call last):   File "<input>", line 8, in <module> TypeError: scrape_property() got an unexpected keyword argument 'property_type'

### ISSUE THREAD

**Issue by mlee33-nor** [Bunsly/HomeHarvest#105]
Traceback (most recent call last):
  File "<input>", line 8, in <module>
TypeError: scrape_property() got an unexpected keyword argument 'property_type'

**Comment by cullenwatson** [comment]
you must be on an old version

do 
```py
pip show homeharvest
```
whats the version?

**Comment by cullenwatson** [comment]
yep just tried and its fine. so 

```bash
pip install -U homeharvest --force-reinstall
```
