### ISSUE TITLE
>50% of property types in Austin marked "other"

### ISSUE THREAD

**Issue by jgrosek** [Bunsly/HomeHarvest#35]
<img width="752" alt="Screen Shot 2023-10-16 at 9 13 23 PM" src="https://github.com/ZacharyHampton/HomeHarvest/assets/28078898/f1ce9a8e-c3f4-43d0-b2c9-45b70813e209">

**Comment by cullenwatson** [comment]
interesting, will look into it tmw

**Comment by cullenwatson** [comment]
Using an old version of HomeHarvest, try `pip install -U homeharvest`. You can verify that you have the latest version number with `pip show homeharvest`. The new field is `style`.  
  
`Austin, for_sale` search,  
  
![image](https://github.com/Bunsly/HomeHarvest/assets/78247585/dee51e2d-ef10-4735-8921-51142c7b8924)
