### ISSUE TITLE
Tags/Description of a property

### ISSUE THREAD

**Issue by reidelkins** [Bunsly/HomeHarvest#36]
Can the search params be modified to include the dict of Tags for each property as well as the long paragraph like description. Additional info like the property details section which is shown on an individual listing would be great as well.

**Comment by cullenwatson** [comment]
Hey @reidelkins , can you show me an example of what Tags and "additional info" you're trying to search/retrieve?

**Comment by reidelkins** [comment]
A true entertainer's dream home.
Boasting with over 3000 SqFt, .98 acres, roof top deck, balcony, your own private floating dock, massive outdoor patio and a beautiful, enclosed swimming pool. With large amounts of paver parking, RV connections and a place to charge your electric car, this house truly...

Property features
Bedrooms

Bedrooms: 5
Bathrooms

Total Bathrooms: 2
Full Bathrooms: 2
1/2 Bathrooms: 1
Interior Features

Breakfast Bar
Breakfast Nook
Ceiling Fan(s)
Flooring: Carpet, Laminate
Appliances

Washer
Refrigerator
Dishwasher
Disposal
Microwave
Garage Door Opener
Dryer
Heating and Cooling

Cooling Features: Central, Central Air
Exterior and Lot Features

Balcony - Screened
Balcony - Unscreened
Deck
Fire Pit
Porch/Patio - Screened
Road Surface Type: Asphalt
Pool and Spa

Pool Features: Pool Cover, Salt System, Concrete, Equipment Included, Screened, Electric Heat
Waterfront and Water Access

Canal Navigation
Dock Private
Land Info

Cul-De-Sac
Wooded
Lot Size Acres: 0.98
Lot Size Square Feet: 42689
Garage and Parking

Garage Spaces: 2
Parking Features: RV/Boat Space (Pvt), Electric Vehicle Charging Station(s)
Home Features

View: Pool, View - West, View - South, Wooded, Canal
Security Features

Security System Owned, Security System
School Information

Elementary School: Tropical
High School: Merritt Island
Middle School: Jefferson
Homeowners Association

Calculated Total Monthly Association Fees: 0
Association Name: HARBOR OAKS
Other Property Info

Source Listing Status: Coming Soon
County: Brevard
Tax Year: 2023
Source Property Type: Residential
Area: 254 - Newfound Harbor
MLS Area Minor: 254 - Newfound Harbor
Source Neighborhood: HARBOR OAKS
Parcel Number: 25-37-07-78-00000.0-0009.00
Subdivision: HARBOR OAKS
Property Subtype: Single Family Detached
Source System Name: C2C
Building and Construction

Total Square Feet Living: 3107
Year Built: 1989
Building Area Total: 3787
Construction Materials: Wood Siding, Stucco
Property Age: 34
Roof: Asphalt
Architectural Style: 2 Story
Utilities

Sewer: Sewer
Cable Available

Here's all the extra details I'm talking about from https://www.realtor.com/realestateandhomes-detail/1725-Harbor-Oaks-Pl_Merritt-Island_FL_32952_M60087-35357?from=srp-list-card

I got the tags working just by adding it at the root level of the area query

**Comment by cullenwatson** [comment]
@reidelkins can you open a PR since you say you got the tags working and I'll take a look at it? Also the description we previously had but then removed due to real estate people telling us it gives the data a bad look as no high quality data from a MLS would provide that
