### ISSUE TITLE
Property street name is missing N/E/W/S Directions

### ISSUE THREAD

**Issue by dino1729** [Bunsly/HomeHarvest#41]
In the latest homeharvest version (0.3.8), the property's street name in the scrapped data is missing the direction:

19754 Sonia Ln

instead of 

19754 SW Sonia Ln

**Comment by ZacharyHampton** [comment]
Hey, could you give an example search? I will fix this ASAP.

**Comment by dino1729** [comment]
Hi,

Thanks for your quick reply.

Here is an example code:
from homeharvest import scrape_property
from datetime import datetime

# Generate filename based on current timestamp
current_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
filename = f"HomeHarvest_{current_timestamp}.csv"

properties = scrape_property(
    location="97007",
    listing_type="sold",  # or (for_sale, for_rent)
    past_days=30,  # sold in last 30 days - listed in last x days if (for_sale, for_rent)
    # pending_or_contingent=True # use on for_sale listings to find pending / contingent listings
    # mls_only=True,  # only fetch MLS listings
    # proxy="http://user:pass@host:port"  # use a proxy to change your IP address
)
print(f"Number of properties: {len(properties)}")

# Export to csv
properties.to_csv(filename, index=False)
print(properties.head())

The resultant csv file doesn't have the directions in the "street" column for any of the line item.


<img width="792" alt="image" src="https://github.com/Bunsly/HomeHarvest/assets/39465454/5a7ac69d-eb94-47b9-b02c-aa3e5907878d">
