### ISSUE TITLE
Tech-Hobbyist Realtor Request

### ISSUE THREAD

**Issue by dmr5090** [Bunsly/HomeHarvest#45]
Hi there. I'm a licensed Realtor and tech hobbyist. I've been playing with the HomeHarvest script in python and it's incredible. Thank you so much for putting this together!

I'm reaching out with a request and a few questions.

Request: Is there any possibility of adding home condition as an additional attribute that can be returned? Normally, the MLS will have something like "Good", "Excellent", etc.
Question 1: Is there an upper limit to radius or past_days?
Question 2: Are there limits on the property types returned? For example, does the search exclude land? Multifamily properties? (I'm trying to get the HomeHarvest results to match my search results on Realtor.com and am getting close by playing with property type filters but not yet finding a precise match.)

Thank you again for this library - it's absolutely incredible.

**Comment by ZacharyHampton** [comment]
Hey, thanks for using this.

Regarding your request, we can look into this and see if this field exists.

The only limit I know of is that there can only be a max of 10k homes returned, so fine tuning these parameters to get the full amount of homes (if over 10k) is important.

I do not believe we have any property type limits.

**Comment by dmr5090** [comment]
Hey @ZacharyHampton, thanks for the reply! Looking forward to hearing more on property condition.

One additional question: For Pending and Sold properties, is there an attribute available for _pending_date_? I see there's a field for _days_on_mls_, which is fine as a proxy for DOM. But technically, DOM is days until pending, not days until sold (_last_sold_date_ - _list_date_). Without knowing the _pending_date_, I don't think I'll be able to nail down DOM.

Thanks again, and happy new year!

**Comment by dmr5090** [comment]
Hey @ZacharyHampton, happy new year! Hope all's well.

Just circling back on the above. Also curious if property type is or can be made available as an attribute (ie, land, multifamily, new construction, etc.)?

Thanks again and cheers!

**Comment by ZacharyHampton** [comment]
@dmr5090 Hey.

There is a pending date. We can add it. We can also add the property type, not sure why it wasn't there in the first place. We don't have condition.

Let me know what you want added, thanks.

**Comment by dmr5090** [comment]
Beautiful, thank you so much @ZacharyHampton! 

Just circling back on the request to add **pending date**. Not meaning to rush you in the least, but curious if you've been able to make any progress? Thanks again!

**Comment by dmr5090** [comment]
Sorry for the multiple comments @ZacharyHampton but another question comes to mind.
I recently ran a search for Columbus, OH (radius = 3, past_days = 360, listing_type = for_rent) and am getting properties returned that are "off market" (ie, no longer available). Here's one example property URL returned by this search: https://www.realtor.com/realestateandhomes-detail/4260949512).

This raises the question of cycling properties off of the for_rent list. I had assumed that once a property for_rent got rented out and was no longer on the market, it would drop from results returned. But it seems off-market listings are still returned.

How should these be handled? One common thread seems to be that list_price is null. If I only wanted properties currently available for_rent, would I exclude records where list_price returns null?

Related: Is there a date field that could be used in the for_rent listing type that identifies when a property that was available for rent went off the market?

Thanks again!

**Comment by dmr5090** [comment]
One more field request if available @ZacharyHampton - Any chance you're able to retrieve the latest year's annual property tax?

**Comment by ZacharyHampton** [comment]
TODO:
Add fields:
Pending date
Property Type

**Comment by dmr5090** [comment]
@ZacharyHampton 
Just circling back 1) to say THANK YOU again for the assist here! 
And 2) Any chance of getting property tax attribute added?
Cheers!
