### ISSUE TITLE
bathroom information not accurate when searching by address

### ISSUE THREAD

**Issue by limsmichael** [Bunsly/HomeHarvest#46]
Searching by address does not give the expected details for `full_baths` and `half_baths` .  POST request returns `null` for bath info, leading to `None` in the dataframe.

### Steps to reproduce
```
properties = scrape_property(
    location="denver co",
    listing_type="for_sale"
)

for idx in range(properties.shape[0]):
        detail = scrape_property(location=properties.iloc[idx]['street'], listing_type='for_sale')
        print(detail.iloc[0]["full_baths"], detail.iloc[0]["half_baths"])
```

### Expected output

```
None None
1 None
3 None
.
.
.
```
### Received output

```
None None
None None
None None
.
.
.
```

**Comment by ZacharyHampton** [comment]
Hey, I will take a look into this.

**Comment by cullenwatson** [comment]
can solve using HomeSearch at  ```https://graph.realtor.com/graphql```, but would be a rewrite
