### ISSUE TITLE
Bunsly Search Error

### ISSUE THREAD

**Issue by joshkulick** [Bunsly/HomeHarvest#49]
403 Client Error: Forbidden for url: https://www.realtor.com/api/v1/rdc_search_srp?client_id=rdc-search-new-communities&schema=vesta

I was trying to lookup a city using your format: CITY,ST (State) and I am getting this error thrown

**Comment by joshkulick** [comment]
![image](https://github.com/Bunsly/HomeHarvest/assets/82619038/c913b216-16c7-4c68-bbe7-241ce9f3586b)
![image](https://github.com/Bunsly/HomeHarvest/assets/82619038/221ea0e4-3f0b-41a6-bc92-4fad118b8f1d)

**Comment by ZacharyHampton** [comment]
Hey, I will look into this, they keep banning our ips, perhaps PX caught up to us.

**Comment by ZacharyHampton** [comment]
Temporarily fixed it. @joshkulick
