### ISSUE TITLE
nearby_schools causes 500 error

### ISSUE THREAD

**Issue by jrgchvs** [Bunsly/HomeHarvest#50]
Trying to add "nearby_schools" to the search query causes an error for the area search. Same error when trying to include "tax_history". Is there a list of valid fields that can be included in the query?

**Comment by cullenwatson** [comment]
Can you share the code with your modification?

**Comment by jrgchvs** [comment]
In homeharvest/core/scrapers/realtor/__init__.py after Lines 354-356 (after the photos call) I include in the string the nearby schools:
nearby_schools {
 schools {
  distance_in_miles
 }
}

**Comment by ZacharyHampton** [comment]
When the syntax is wrong, it causes a 500 error, on Realtor specifically.
