### ISSUE TITLE
`KeyError: 'centroid'` for certain addresses when setting `radius` parameter in `scrape_property`

### ISSUE THREAD

**Issue by adobles96** [Bunsly/HomeHarvest#51]
Sometimes I get a `KeyError: 'centroid'` coming from [this line](https://github.com/Bunsly/HomeHarvest/blob/03198428de87b46f377dbb69a0949e9fe09e1367/homeharvest/core/scrapers/realtor/__init__.py#L570C69-L570C71) when using `scrape_property` with the `radius` parameter. It seems the key is missing from `location_info` which is determined by a call to this API endpoint: `"https://parser-external.geo.moveaws.com/suggest"` in `handle_location`. I'm guessing centroid is missing b/c the latter endpoint can't match the address to coordinates? If so, should we raise an exception instead?

**Comment by ZacharyHampton** [comment]
@adobles96 Thanks for the issue, I'll look into it.

**Comment by ZacharyHampton** [comment]
Fixed and released.
