### ISSUE TITLE
Zillow/Redfin removed?

### ISSUE THREAD

**Issue by cradcore** [Bunsly/HomeHarvest#54]
In the GitHub keywords, previous issues/pull requests and the git history I see both mentions of zillow and redfin scraping. However at first glance it looks like the scrapers were removed in version 3.0 (29664e4eee3db0ef978b68d28ffe45155142d7dc)

Are these sites no longer supported or is there just a different way to scrape from them that I'm missing?

**Comment by ZacharyHampton** [comment]
We removed support for them. There isn't much purpose of aggregating real estate listings, other than for the purpose of FSBO.

**Comment by cradcore** [comment]
@ZacharyHampton Isn't that the point of HomeHarvest? I was looking to use HomeHarvest to scrape the data from these sites and get rent trends in my area, and while realtor.com does have some, the vast majority of rentals are on Zillow

**Comment by ZacharyHampton** [comment]
The previous purpose was that, yes. But we realized there isn't much point of aggregating the data, as its mostly the same. Realtor.com is much more scalable for open source, doing so with Zillow is a bit harder.

**Comment by sabatale** [comment]
@cradcore Doesn't work. Returns 202.

**Comment by cradcore** [comment]
@sabatale 
```
#!/bin/env python3

from homeharvest import scrape_property

data = scrape_property(
    location="90210",
    site_name="zillow",
    listing_type="for_rent"
)
print("Properties: {}".format(len(data)))
```

```
Properties: 321
```
Working just fine for me just fine but you can add an issue to my github with more details, including what youre trying to run and the logs, if you want

**Comment by sabatale** [comment]
My bad, it looks like NordVPN IPs are blacklisted. That's why.

Cheers! (ps. issues on your repo are disabled)
