### ISSUE TITLE
Any way to pull realtor data with sold properties or listings?

### ISSUE THREAD

**Issue by Phillie419** [Bunsly/HomeHarvest#58]
I am working on learning python and found this project. It is really awesome!
 I was able to modify the output name of the excel file based on the parameters i was searching for.
I am trying to find a way to add realtor names to the list of sold properties. I looked through the html on the site and found it is under <strong data-testi id or Seller-sc-okw218-0 jDsXJc. Looking through your code it looks like it goes directly to the api so the names might not be the same on the site as what would show up on the json payload.  

Is there a way to run a query to the api to see what field names they have?  or can realtor fields be be added? I was trying to do it myself but have a lack up understanding in how this all works together at this point. 

Sorry if this is not the place to post this but am not sure what to do without the fieldnames.

**Comment by ZacharyHampton** [comment]
Change your listing type to sold to get sold properties.

**Comment by Phillie419** [comment]
Hey thanks for the quick response.  I want to add the realtors who worked on the deal to the results. Pulling a list of sold property works perfectly but the agent info is not being looked for.

**Comment by ZacharyHampton** [comment]
I am not sure the data is easy to get in a fast manner, I can check again if you'd like.

**Comment by ZacharyHampton** [comment]
@cullenwatson added agents.
