### ISSUE TITLE
Query listings for entire state

### ISSUE THREAD

**Issue by 2thesimplexity** [Bunsly/HomeHarvest#60]
I've tested with multiple cities, and the total count in the csv matches with with the count on realtor.com (Select Hide Pending/Contigent)

However, when I tried to query for entire state, the count in the csv is significantly lower than on realtor.com.

Example: 
For state CA:  From HomeHarvest csv < 10,000 listings
On Realtor.com: 78,097 listings

I've tested with other states too, but same observation

**Comment by ZacharyHampton** [comment]
The max results are 10k, use filters such as date from and to, or past days to paginate.
