### ISSUE TITLE
Remove Zillow and Redfin from repository tags.

### ISSUE THREAD

**Issue by gibsonpil** [Bunsly/HomeHarvest#62]
Since Zillow and Redfin support has been dropped, there is little sense in keeping tags such as `zillow`, `zillow-scraper`, `redfin`, and `redfin-scraper` attached to the repository. 

They should be removed to avoid causing confusion.

**Comment by ZacharyHampton** [comment]
It helps people that may want real estate data find our project, even if we no longer support the sites. The data is generally the same.
