### ISSUE TITLE
Additional attributes of property

### ISSUE THREAD

**Issue by LasithaSiriweera** [Bunsly/HomeHarvest#63]
Thank you for providing this tool for individual home buyers to search for properties; it's really helpful. I have a question about the schema. Are we utilizing all the attributes of the schema to fetch data? If not, could you please guide me on how to access the full schema of the Realtor data source? I need to fetch additional data about properties such as property descriptions, listing brokerage info, listing agent info, property tax rate, property tax amount estimate, number of units, etc. Your assistance would be greatly appreciated.

**Comment by ZacharyHampton** [comment]
With how it's built right now, you need to fork the project and change the graphql queries, or possibly the flow to get different data.
