### ISSUE TITLE
Scrape an important value 

### ISSUE THREAD

**Issue by ahmediniesta** [Bunsly/HomeHarvest#73]
this is a great project, i want to ask if you are able to scrape the value "**Quantarium**" in realtor.com. 

Regards,

**Comment by cullenwatson** [comment]
example? @ahmediniesta

**Comment by ZacharyHampton** [comment]
@cullenwatson should be the home estimate provider, Quantarium.

Would zestimate work here? @ahmediniesta

**Comment by cullenwatson** [comment]
added estimate value. if this is not what you wanted, reopen thanks
