### ISSUE TITLE
scrape_properties() only returning a small list of "relevant listings"

### ISSUE THREAD

**Issue by farrantch** [Bunsly/HomeHarvest#78]
It appears that Realtor.com splits its search results into a small section of "Relevant listings" and a longer section with the rest of the properties. The scrape_property function only returns the small first section of listings, not the 2nd section of longer listings.

**Comment by ZacharyHampton** [comment]
Hey @farrantch 

Can you send over a code example, along with the screenshots with the same results from the site?

Thanks.

**Comment by farrantch** [comment]
Except that it doesn't matter what I increase the radius to; I still get the same number of results.

**Comment by ZacharyHampton** [comment]
I believe radius is only supported for individual addresses.

**Comment by farrantch** [comment]
I also tried that and it didn't work :(

**Comment by ZacharyHampton** [comment]
Can you send the code sample (not a screenshot) here with the part that "doesn't work"?

**Comment by farrantch** [comment]
I confirmed that using a specific address along with a radius still doesn't return more than ~10 results for me.

`def fetch_listings_homeharvest():
    logger.info("Fetching properites via HomeHarvest...")
    properties = scrape_property(
        location = "9161 Butler Rd, Meriden KS 66512",
        listing_type = "for_sale",
        mls_only = False,
        extra_property_data = True,
        radius = 60
    )
    logger.info("Found %i properties.", len(properties))
    print(properties)
    return properties
`

**Comment by cullenwatson** [comment]
can you share where you navigated to in the search to get 293 homes? not seeing that in the site

https://www.realtor.com/realestateandhomes-search/Meriden_KS
