### ISSUE TITLE
Estimate of home value

### ISSUE THREAD

**Issue by Amir-SDSU** [Bunsly/HomeHarvest#79]
Hi,

I was wondering if realtor.com provides home value estimates as one of their fields. If so, could you please add it? Redfin and Zillow provide home value estimates.

Thank you,
Amir

**Comment by ZacharyHampton** [comment]
Hey Amir, 

We've already added the field. Try updating if you don't see it.

**Comment by Amir-SDSU** [comment]
Hi Zachary,

Great!  I just updated it and I see the new fields.   

Thank you very much,
Amir
