### ISSUE TITLE
Seeking help

### ISSUE THREAD

**Issue by Yanruoxi001** [Bunsly/HomeHarvest#80]
It seems that there is an issue with the web scraping tool at tryhomeharest.com. May I ask what the reason is? 

The error is as follows: HTTPSConnectionPool(host='parser-external.geo.moveaws.com', port=443): Max retries exceeded with url: /suggest?input=San+Francisco%2C+CA&client_id=for-sale&limit=1&area_types=city%2Cstate%2Ccounty%2Cpostal_code%2Caddress%2Cstreet%2Cneighborhood%2Cschool%2Cschool_district%2Cuniversity%2Cpark (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))

**Comment by ZacharyHampton** [comment]
Hey,

Very sorry, forgot to renew proxies. I'll have this up by tonight.

Thanks you for pointing this out and reminding me.

**Comment by ZacharyHampton** [comment]
Fixed.

**Comment by Yanruoxi001** [comment]
That's it, thank you very much for your work!
