### ISSUE TITLE
Question about emails

### ISSUE THREAD

**Issue by mlee33-nor** [Bunsly/HomeHarvest#84]
HI I noticed some of the emails are pulling ones like INFO@Homesmart.com but when you look at the realtors say redfin listing description it shows their real email, curious where are the emails being pulled from that are used for this?

**Comment by ZacharyHampton** [comment]
Can you give an example property for me and its associated realtor and Redfin listing? I can see if realtor provides the "better" email and migrate to it.

**Comment by mlee33-nor** [comment]
I can try i had a situation earlier where like i emailed the agent but it wasn't her listing so was curious how the emails where pulled the property was  4808 N 24th St AZ the email it gave juliehill1984@gmail.com was associated to a Julie Johnson who said not her listing. Was wondering like how it pulled that specific email for the listin.

**Comment by mlee33-nor** [comment]
https://www.redfin.com/AZ/Phoenix/4808-N-24th-St-85016/unit-1326/home/28156416 --- thats a good example of one that has the real agents email aka juliesequoia1@gmail.com instead of juliehill1984@gmail.com which was a diff agent then the real one listing

**Comment by mlee33-nor** [comment]
close this if possible!
