### ISSUE TITLE
Apartment style type listings return NaN values

### ISSUE THREAD

**Issue by itsjacobhere** [Bunsly/HomeHarvest#86]
Nearly all returned features for listings with the Apartment style type return Nan for nearly all features including: list price, beds, full_baths, sqft, year_built, etc.. This doesn't occur for every Apartment style listing, some do return features with filled values but the majority are NaN.

see example of the proportion of NaN values for each style type:
![Screenshot 2024-06-21 225855](https://github.com/Bunsly/HomeHarvest/assets/34584341/f3c54f2a-0b0f-427f-9c90-234746d0b6d3)

**Comment by ZacharyHampton** [comment]
Thanks for the issue.

I'll take a look and see if this is an issue on our end.

**Comment by itsjacobhere** [comment]
Yeah I figured it could be an issue with the data source, I was able to find the listings that returned Nan on realtor.com and all the data is there, so I'm not sure if it's an issue retrieving it or something else.

**Comment by ZacharyHampton** [comment]
Likely an issue with us then. Can you send a code example where you're getting many NaNs and a listing in the bunch that has the proper data on site?

**Comment by itsjacobhere** [comment]
Yes I can send a more detailed example when I get home Monday or Tuesday! If I recall it was happening with pretty simple queries with the "for_rent" type and the returned apartments were mostly Nan values. I was primarily looking at San Diego, CA but it was happening for other locations too. I was able to just Google the full address and find out on realtor.com with everything there

**Comment by ZacharyHampton** [comment]
Added list_price min and max.

This issue was occurring on properties that have floor plans, with multiple units. On realtor, these are displayed as a range, so I have given the min and max prices, similar to realtor.
