### ISSUE TITLE
Historical listings not included if they didn't sell

### ISSUE THREAD

**Issue by kylejcaron** [Bunsly/HomeHarvest#87]
Thanks for building this tool! I noticed that historical listings that didn't sell don't end up getting scraped under `listing_type='for_sale'`. It would be great (and more reflective of the history) to include all listings whether they sold or not

**Comment by ZacharyHampton** [comment]
Hey, thanks for the issue.

I assume, what you'd be asking for here is more of an "all" listing type? So you can do a search and get every listing?

**Comment by kylejcaron** [comment]
> Hey, thanks for the issue.
> 
> I assume, what you'd be asking for here is more of an "all" listing type? So you can do a search and get every listing?

yes exactly! In the meantime, I realized that I can manually enter addresses to get their listing regardless so its no problem for me, but I personally think this would be a good feature!

**Comment by cullenwatson** [comment]
can you give an example of a listing that didnt sell @kylejcaron

**Comment by cullenwatson** [comment]
closing as no response
