### ISSUE TITLE
Not getting any listing result back

### ISSUE THREAD

**Issue by u48487** [Bunsly/HomeHarvest#89]
Starting today, the scrapper is not returning any listing result.
Not really sure what is the exact issue.

**Comment by u48487** [comment]
I did a little bit more digging into the issue. It seems like the issue is from "Realtor.com". The website is not returning any listing. So technically speaking, this code is doing what it is supposed to do, returning "0" listing found.

**Comment by kylejcaron** [comment]
> Starting today, the scrapper is not returning any listing result. Not really sure what is the exact issue.

+1 to this issue, hoping its a temporary outage
