### ISSUE TITLE
Listing "for_rent" properties sometimes result in issues: `NoneType` object has no attribute `replace`

### ISSUE THREAD

**Issue by LichenWang** [Bunsly/HomeHarvest#90]
To reproduce: 

```
scrape_property(
    location="Omaha, NE",
    listing_type="for_rent",  # or (for_sale, for_rent, pending)
    past_days=3000, 
    mls_only=False
    )
```

Results in `NoneType` object has no attribute `replace`

homeharvest==0.3.32

**Comment by LichenWang** [comment]
Most likely because of 

`primary_photo = primary_photo_href.replace("s.jpg", "od-w480_h360_x2.webp?w=1080&q=75")`

when is None :)

**Comment by ZacharyHampton** [comment]
Hey, I had fixed this a couple days ago, just hadn't pushed as I wanted to get to some other things. I'm going to push in a moment.

**Comment by LichenWang** [comment]
Hey sorry is this pushed? I am still seeing this issue on `v0.3.33` probably it is not pushed yet?
