### ISSUE TITLE
Contingnet and pending being pulled through for For_sale

### ISSUE THREAD

**Issue by mlee33-nor** [Bunsly/HomeHarvest#92]
as subject says ive been getting alot of Contingent and Pending being put in my list even tho i have it as for _sale

example of two

 1139 W Vineyard Plains Dr,
San Tan Valley, AZ 85143

730 N Sonora St,
Coolidge, AZ 85128

**Comment by ZacharyHampton** [comment]
To omit these properties, use the exclude_pending parameter.
