### ISSUE TITLE
Zoning and Parcel info

### ISSUE THREAD

**Issue by silentuser** [Bunsly/HomeHarvest#95]
Hello Zachary Hampton,

The zoning info is included for pretty much every single listing in the US and is a very useful piece of information. So is the APN or the parcel number.

Any chance you can add it to the library or point me in the right direction as to what files to change? I am happy to contribute the code back to the community.

**Comment by ZacharyHampton** [comment]
I cannot find this information on Realtor, if you have, could you let me know where and how to reproduce?
