### ISSUE TITLE
Replace method on a NoneType object

### ISSUE THREAD

**Issue by dmr5090** [Bunsly/HomeHarvest#96]
Hey HomeHarvest team, quick question here. It seems that some cities may contain data that cause no data to be returned.

For example, when I run this script for Reading, PA, I get results. But when I run the exact same script for Spokane, WA, I get the following error:

**AttributeError: 'NoneType' object has no attribute 'replace'**

It seems to be trying to call the replace method on a NoneType object, which suggests that primary_photo_href may be None when the method is called. Script below. Curious if you replace city with 'Spokane' and state with 'WA' if you're able to reproduce? Looks like some recent activity on primary_photo; hopefully this helps. Thanks!

`from homeharvest import scrape_property
import pandas as pd

def scrape_data(location, listing_type, past_days, radius):
    try:
        return scrape_property(location=location, listing_type=listing_type, past_days=past_days, radius=radius)
    except Exception as e:
        print(f"An error occurred while scraping data: {e}")
        return []

city = 'Reading'
state = 'PA'
past_days = 360
radius = 3.0

location = f'{city}, {state}'

properties = scrape_data(location=location, listing_type='for_rent', past_days=past_days, radius=radius)

df_result = pd.DataFrame(properties)

if not df_result.empty:
    print(df_result)
else:
    print("No properties found or an error occurred.")`

**Comment by ZacharyHampton** [comment]
Thanks for the issue, this seems like a simple fix, I'll try to push it out today.

**Comment by ZacharyHampton** [comment]
@dmr5090 I have no issues, what is your HomeHarvest version?

See such with the following command:
`pip show homeharvest`

If it's not **v0.3.33**, you are not up to date.

Update with the below command:
`pip install -U homeharvest`

**Comment by dmr5090** [comment]
Facepalm - Yep, no issues after version update. Will close. Apologies!
