### ISSUE TITLE
Running it directly through python automatically

### ISSUE THREAD

**Issue by jkessous** [Bunsly/HomeHarvest#97]
Hi
First of all i want to thank you for this amazing tool.
i am trying run this as a python script that will run automatically but I guess I am doing something wrong.
it works great with PYCharm but when I try to run it through the command line or terminal I am getting errors line 1 with the import.

any idea how I can solve this?

also - do you know how I can extract the data to a database and not CSV file.

thanks

**Comment by cullenwatson** [comment]
can you paste the error

and to mongo database running locally

```py
from pymongo import MongoClient
from homeharvest import scrape_property

database = MongoClient()
properties = scrape_property(
  location="dallas, tx",
  past_days=30, 
)
data_dict = properties.to_dict("records")
database['mydatabase']['properties'].insert_many(data_dict)
```

**Comment by jkessous** [comment]
amazing. thanks for the help.

**Comment by jkessous** [comment]
hi Cullen,
small question regarding the script
every time you run the script it creates a duplicate in the database.
is there an option to avoid the duplicates?
thanks

**Comment by cullenwatson** [comment]
yea just drop the current collection

then
# create index one time
database['mydatabase']['properties'].create_index([('mls_id', 1)], unique=True)

# insert with ordered=False 
try:
    database['mydatabase']['properties'].insert_many(data_dict, ordered=False)
except Exception as e:
    pass

**Comment by jkessous** [comment]
thanks buddy
this is the code i have (i left the credentials for the temp db in case you
want to try it).
first time it runs it is ok.
second time i run i get multiple errors

from pymongo import MongoClient
from homeharvest import scrape_property

database = ***@***.***/?retryWrites=true&w=majority&appName=BlastMyOffersTemp')
properties = scrape_property(
  location="Cleveland, OH",
  listing_type="for_sale",  # or (for_sale, for_rent)
  past_days=100,
)

database['Devops']['properties'].create_index([('mls_id', 1)], unique=True)
data_dict = properties.to_dict("records")
database['Devops']['properties'].insert_many(data_dict, ordered=False)

**Comment by cullenwatson** [comment]
Can you paste the error @jkessous

**Comment by cullenwatson** [comment]
Yes that’s not an error, just saying mongo skipped the duplicate which is desired

**Comment by jkessous** [comment]
ok thanks man
i really appreciate it alot

**Comment by jkessous** [comment]
hey buddy
is there any option that the script will not send all of this to the console
.com/5d9a07cf3dd06104c1b54cda8d6dcd75l-m2574524585od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/5d9a07cf3dd06104c1b54cda8d6dcd75l-m1770705647od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/5d9a07cf3dd06104c1b54cda8d6dcd75l-m2143427487od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/5d9a07cf3dd06104c1b54cda8d6dcd75l-m2446523634od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/5d9a07cf3dd06104c1b54cda8d6dcd75l-m3885976941od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/5d9a07cf3dd06104c1b54cda8d6dcd75l-m555459484od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/5d9a07cf3dd06104c1b54cda8d6dcd75l-m298208096od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/5d9a07cf3dd06104c1b54cda8d6dcd75l-m1072333880od-w480_h360_x2.webp?w=1080&q=75',
'_id': ObjectId('66f94de10996851505dea9fd')}}, {'index': 674, 'code':
11000, 'errmsg': 'E11000 duplicate key error collection:
Cleveland.Cuyahoga_county index: mls_id_1 dup key: { mls_id: "5072335" }',
'keyPattern': {'mls_id': 1}, 'keyValue': {'mls_id': '5072335'}, 'op':
{'property_url': '
https://www.realtor.com/realestateandhomes-detail/3523-W-125th-St_Cleveland_OH_44111_M44306-55129',
'property_id': '4430655129', 'listing_id': '2972539457', 'mls': 'NEOH',
'mls_id': '5072335', 'status': 'PENDING', 'text': 'Nice 5X5 up and down
duplex. Some updating has been done. Needs a good cleaning and paint and
could be a very nice home. Tenants are month to month and pay below market
price.', 'style': 'MULTI_FAMILY', 'full_street_line': '3523-3525 W 125th
St', 'street': '3523-3525 W 125th St', 'unit': None, 'city': 'Cleveland',
'state': 'OH', 'zip_code': '44111', 'beds': 4, 'full_baths': 2,
'half_baths': None, 'sqft': 2808, 'year_built': 1919, 'days_on_mls': 6,
'list_price': 155000, 'list_price_min': None, 'list_price_max': None,
'list_date': '2024-09-23', 'sold_price': 24000, 'last_sold_date':
'2010-02-25', 'assessed_value': 27590, 'estimated_value': 152963,
'new_construction': False, 'lot_sqft': 3676, 'price_per_sqft': 55,
'latitude': 41.456897, 'longitude': -81.774416, 'neighborhoods':
'Jefferson, West Park', 'county': 'Cuyahoga', 'fips_code': '39035',
'stories': 2, 'hoa_fee': 0, 'parking_garage': 1, 'agent_id': '27630',
'agent_name': 'SUSAN R. BRADLEY - BRADLEY REAL ESTATE TEAM', 'agent_email':
***@***.***', 'agent_phones': [{'ext': None,
'primary': True, 'type': 'Mobile', 'number': '2165331040'}],
'agent_mls_set': 'A-NEOH-231409', 'agent_nrds_id': '657000957',
'broker_id': '4549841', 'broker_name': 'Classic Realty Group Broker',
'builder_id': None, 'builder_name': None, 'office_id': '3071276',
'office_mls_set': 'O-NEOH-2698', 'office_name': 'Classic Realty Group,
Inc.', 'office_email': ***@***.***', 'office_phones':
[{'number': '(440) 526-4200', 'type': 'Office', 'primary': True, 'ext':
None}], 'nearby_schools': 'Cleveland Metropolitan School District',
'primary_photo': '
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m2219622000od-w480_h360_x2.webp?w=1080&q=75',
'alt_photos': '
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m2219622000od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m878920128od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m1328475469od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m2745990337od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m3075430314od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m3335615438od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m3594235293od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m2903787701od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m2615250937od-w480_h360_x2.webp?w=1080&q=75,
http://ap.rdcpix.com/2da584fc5dbf958cc4adaf4cbb03e05bl-m2740349469od-w480_h360_x2.webp?w=1080&q=75',
'_id': ObjectId('66f94de10996851505dea9fe')}}], 'writeConcernErrors': [],
'nInserted': 2, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved':
0, 'upserted': []}

and send it to a log file ?

i am trying to add to the script an email alert that it will alert if it
succeeded or failed but since all the time it mentions that Process
finished with exit code 0 the scirpt things it failed and send me an
alrert of a failure.
thanks

**Comment by cullenwatson** [comment]
yea just dont print the error with pass

```py
try:
    database['mydatabase']['properties'].insert_many(data_dict, ordered=False)
except Exception as e:
    pass
```

**Comment by jkessous** [comment]
hey
thanks for the prompt reply
i dont have any print in the script.
this is the script i have:


from pymongo import MongoClient
from homeharvest import scrape_property
import time
import schedule


database = ***@***.***/?retryWrites=true&w=majority&appName=BlastMyOffersTemp')
properties = scrape_property(
  location="Cuyahoga county",
  listing_type="for_sale",  # or (for_sale, for_rent)
  past_days=2,
)
database['Cleveland']['Cuyahoga_county'].create_index([('mls_id', 1)],
unique=True)
#database['Cleveland']['Cuyahoga_county'].create_index([('mls_id',
1)], unique=True) - should run only once
data_dict = properties.to_dict("records")
database['Cleveland']['Cuyahoga_county'].insert_many(data_dict, ordered=False)
