### ISSUE TITLE
advertisers

### ISSUE THREAD

**Issue by macros144444** [Bunsly/HomeHarvest#99]
Should this be including advertisers information in the output file?  I'm thinking so but it doesn't show up in my outputted file.

**Comment by ZacharyHampton** [comment]
It does include advertisers.

**Comment by macros144444** [comment]
Ok just called the default.
properties = scrape_property(
  location="Phoenix, AZ",
  listing_type="for_rent",  # or (for_sale, for_rent, pending)
)
This is the outputted columns.
property_url,mls,mls_id,status,style,street,unit,city,state,zip_code,beds,full_baths,half_baths,sqft,year_built,list_price,list_date,sold_price,last_sold_date,lot_sqft,price_per_sqft,latitude,longitude,stories,hoa_fee,parking_garage

**Comment by ZacharyHampton** [comment]
What version of homeharvest are you on?

**Comment by macros144444** [comment]
0.3.2

**Comment by macros144444** [comment]
I just used the following:

pip install -U homeharvest

**Comment by ZacharyHampton** [comment]
Did that fix your issue?

**Comment by macros144444** [comment]
no.

**Comment by macros144444** [comment]
$ pip install -U homeharvest

OUTPUT
Collecting homeharvest
  Using cached homeharvest-0.3.2-py3-none-any.whl.metadata (9.1 kB)

**Comment by macros144444** [comment]
Actually got it to work.  I was using python 3.13.

**Comment by ZacharyHampton** [comment]
That would do it. I'll see if we can support above 3.11.
